spring.application.name=payment-service
#spring.application.name=payment-service

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/nearmart_payment_db
spring.datasource.username=root
spring.datasource.password=J7499#jya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzpxxxxxx
razorpay.key.secret=xxxxxx