spring.application.name=backend

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/nearmart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=root123
=======
spring.datasource.password=J7499#jya
>>>>>>> eae9d6c (Add Razorpay payment service and frontend integration)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090
# ==========================
# JWT Configuration
# ==========================

jwt.secret=NearMartSecretKeyForJWTAuthentication2026SecureKey123456
jwt.expiration=86400000


